# This is a basic workflow to help you get started with Actions

name: AssignmentCI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
    # branches: [ main ]
  # pull_request:
    # branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      filename:
        description: "Define File Name (with extension, e.g. .txt)"
        required: true
        default: 'sample.txt'
        
      toReplace:
        description: "Insert the string to be replaced"
        required: true
      
      toReplaceWith:
        description: "Insert the string to be replaced with"
        required: true

env:
  SCRIPTS_DIR: scripts

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Test-build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Execute Test Python
        run : | 
          python $GITHUB_WORKSPACE/test.py
      
      - name: Execute Test Python - method 2
        run : | 
          python test.py
    
  Dev-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Go to Scripts directory
        run: | 
          cd ${{ env.SCRIPTS_DIR }}
          ls
      
      - name: Execute Python Script
        run : | 
          python "replaceFileString.py ${{ github.event.inputs.filename }} ${{ github.event.inputs.toReplace }} ${{ github.event.inputs.toReplaceWith }}"
        
